---
- hosts: localhost
  remote_user: felippe
  become: yes
  tasks:
  - name: "Instala o pacote de integracao Docker com Python"
    apt:
      name: python-docker
      state: present
  - name: cria o diretório onde a base de dados MySQL sera salva
    file:
      path: /dados-banco
      state: directory
      owner: root
      group: root
      mode: 0755
  - name: "Executa o container MySQL"
    docker_container:
      name: banco
      image: mysql:5.6
      env:
          MYSQL_ROOT_PASSWORD: senha123
      volumes:
        - /dados-banco:/var/lib/mysql
  - name: "Executa o container WordPress"
    docker_container:
      name: wordpress
      image: wordpress
      links:
        - "banco:mysql"
      ports:
        - "80:80"
